// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ONSdigital/dis-redirect-api/models"
	"github.com/ONSdigital/dis-redirect-api/sdk/go"
	apiError "github.com/ONSdigital/dis-redirect-api/sdk/go/errors"
	healthcheck "github.com/ONSdigital/dp-api-clients-go/v2/health"
	health "github.com/ONSdigital/dp-healthcheck/healthcheck"
	"sync"
)

// Ensure, that ClienterMock does implement sdk.Clienter.
// If this is not the case, regenerate this file with moq.
var _ sdk.Clienter = &ClienterMock{}

// ClienterMock is a mock implementation of sdk.Clienter.
//
//	func TestSomethingThatUsesClienter(t *testing.T) {
//
//		// make and configure a mocked sdk.Clienter
//		mockedClienter := &ClienterMock{
//			CheckerFunc: func(ctx context.Context, check *health.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			DeleteRedirectFunc: func(ctx context.Context, options sdk.Options, id string) apiError.Error {
//				panic("mock out the DeleteRedirect method")
//			},
//			GetRedirectFunc: func(ctx context.Context, options sdk.Options, key string) (*models.Redirect, apiError.Error) {
//				panic("mock out the GetRedirect method")
//			},
//			GetRedirectsFunc: func(ctx context.Context, options sdk.Options) (*models.Redirects, apiError.Error) {
//				panic("mock out the GetRedirects method")
//			},
//			HealthFunc: func() *healthcheck.Client {
//				panic("mock out the Health method")
//			},
//			PutRedirectFunc: func(ctx context.Context, options sdk.Options, id string, payload models.Redirect) apiError.Error {
//				panic("mock out the PutRedirect method")
//			},
//			URLFunc: func() string {
//				panic("mock out the URL method")
//			},
//		}
//
//		// use mockedClienter in code that requires sdk.Clienter
//		// and then make assertions.
//
//	}
type ClienterMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, check *health.CheckState) error

	// DeleteRedirectFunc mocks the DeleteRedirect method.
	DeleteRedirectFunc func(ctx context.Context, options sdk.Options, id string) apiError.Error

	// GetRedirectFunc mocks the GetRedirect method.
	GetRedirectFunc func(ctx context.Context, options sdk.Options, key string) (*models.Redirect, apiError.Error)

	// GetRedirectsFunc mocks the GetRedirects method.
	GetRedirectsFunc func(ctx context.Context, options sdk.Options) (*models.Redirects, apiError.Error)

	// HealthFunc mocks the Health method.
	HealthFunc func() *healthcheck.Client

	// PutRedirectFunc mocks the PutRedirect method.
	PutRedirectFunc func(ctx context.Context, options sdk.Options, id string, payload models.Redirect) apiError.Error

	// URLFunc mocks the URL method.
	URLFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Check is the check argument value.
			Check *health.CheckState
		}
		// DeleteRedirect holds details about calls to the DeleteRedirect method.
		DeleteRedirect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Options is the options argument value.
			Options sdk.Options
			// ID is the id argument value.
			ID string
		}
		// GetRedirect holds details about calls to the GetRedirect method.
		GetRedirect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Options is the options argument value.
			Options sdk.Options
			// Key is the key argument value.
			Key string
		}
		// GetRedirects holds details about calls to the GetRedirects method.
		GetRedirects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Options is the options argument value.
			Options sdk.Options
		}
		// Health holds details about calls to the Health method.
		Health []struct {
		}
		// PutRedirect holds details about calls to the PutRedirect method.
		PutRedirect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Options is the options argument value.
			Options sdk.Options
			// ID is the id argument value.
			ID string
			// Payload is the payload argument value.
			Payload models.Redirect
		}
		// URL holds details about calls to the URL method.
		URL []struct {
		}
	}
	lockChecker        sync.RWMutex
	lockDeleteRedirect sync.RWMutex
	lockGetRedirect    sync.RWMutex
	lockGetRedirects   sync.RWMutex
	lockHealth         sync.RWMutex
	lockPutRedirect    sync.RWMutex
	lockURL            sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *ClienterMock) Checker(ctx context.Context, check *health.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("ClienterMock.CheckerFunc: method is nil but Clienter.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Check *health.CheckState
	}{
		Ctx:   ctx,
		Check: check,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, check)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedClienter.CheckerCalls())
func (mock *ClienterMock) CheckerCalls() []struct {
	Ctx   context.Context
	Check *health.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		Check *health.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// DeleteRedirect calls DeleteRedirectFunc.
func (mock *ClienterMock) DeleteRedirect(ctx context.Context, options sdk.Options, id string) apiError.Error {
	if mock.DeleteRedirectFunc == nil {
		panic("ClienterMock.DeleteRedirectFunc: method is nil but Clienter.DeleteRedirect was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Options sdk.Options
		ID      string
	}{
		Ctx:     ctx,
		Options: options,
		ID:      id,
	}
	mock.lockDeleteRedirect.Lock()
	mock.calls.DeleteRedirect = append(mock.calls.DeleteRedirect, callInfo)
	mock.lockDeleteRedirect.Unlock()
	return mock.DeleteRedirectFunc(ctx, options, id)
}

// DeleteRedirectCalls gets all the calls that were made to DeleteRedirect.
// Check the length with:
//
//	len(mockedClienter.DeleteRedirectCalls())
func (mock *ClienterMock) DeleteRedirectCalls() []struct {
	Ctx     context.Context
	Options sdk.Options
	ID      string
} {
	var calls []struct {
		Ctx     context.Context
		Options sdk.Options
		ID      string
	}
	mock.lockDeleteRedirect.RLock()
	calls = mock.calls.DeleteRedirect
	mock.lockDeleteRedirect.RUnlock()
	return calls
}

// GetRedirect calls GetRedirectFunc.
func (mock *ClienterMock) GetRedirect(ctx context.Context, options sdk.Options, key string) (*models.Redirect, apiError.Error) {
	if mock.GetRedirectFunc == nil {
		panic("ClienterMock.GetRedirectFunc: method is nil but Clienter.GetRedirect was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Options sdk.Options
		Key     string
	}{
		Ctx:     ctx,
		Options: options,
		Key:     key,
	}
	mock.lockGetRedirect.Lock()
	mock.calls.GetRedirect = append(mock.calls.GetRedirect, callInfo)
	mock.lockGetRedirect.Unlock()
	return mock.GetRedirectFunc(ctx, options, key)
}

// GetRedirectCalls gets all the calls that were made to GetRedirect.
// Check the length with:
//
//	len(mockedClienter.GetRedirectCalls())
func (mock *ClienterMock) GetRedirectCalls() []struct {
	Ctx     context.Context
	Options sdk.Options
	Key     string
} {
	var calls []struct {
		Ctx     context.Context
		Options sdk.Options
		Key     string
	}
	mock.lockGetRedirect.RLock()
	calls = mock.calls.GetRedirect
	mock.lockGetRedirect.RUnlock()
	return calls
}

// GetRedirects calls GetRedirectsFunc.
func (mock *ClienterMock) GetRedirects(ctx context.Context, options sdk.Options) (*models.Redirects, apiError.Error) {
	if mock.GetRedirectsFunc == nil {
		panic("ClienterMock.GetRedirectsFunc: method is nil but Clienter.GetRedirects was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Options sdk.Options
	}{
		Ctx:     ctx,
		Options: options,
	}
	mock.lockGetRedirects.Lock()
	mock.calls.GetRedirects = append(mock.calls.GetRedirects, callInfo)
	mock.lockGetRedirects.Unlock()
	return mock.GetRedirectsFunc(ctx, options)
}

// GetRedirectsCalls gets all the calls that were made to GetRedirects.
// Check the length with:
//
//	len(mockedClienter.GetRedirectsCalls())
func (mock *ClienterMock) GetRedirectsCalls() []struct {
	Ctx     context.Context
	Options sdk.Options
} {
	var calls []struct {
		Ctx     context.Context
		Options sdk.Options
	}
	mock.lockGetRedirects.RLock()
	calls = mock.calls.GetRedirects
	mock.lockGetRedirects.RUnlock()
	return calls
}

// Health calls HealthFunc.
func (mock *ClienterMock) Health() *healthcheck.Client {
	if mock.HealthFunc == nil {
		panic("ClienterMock.HealthFunc: method is nil but Clienter.Health was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHealth.Lock()
	mock.calls.Health = append(mock.calls.Health, callInfo)
	mock.lockHealth.Unlock()
	return mock.HealthFunc()
}

// HealthCalls gets all the calls that were made to Health.
// Check the length with:
//
//	len(mockedClienter.HealthCalls())
func (mock *ClienterMock) HealthCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHealth.RLock()
	calls = mock.calls.Health
	mock.lockHealth.RUnlock()
	return calls
}

// PutRedirect calls PutRedirectFunc.
func (mock *ClienterMock) PutRedirect(ctx context.Context, options sdk.Options, id string, payload models.Redirect) apiError.Error {
	if mock.PutRedirectFunc == nil {
		panic("ClienterMock.PutRedirectFunc: method is nil but Clienter.PutRedirect was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Options sdk.Options
		ID      string
		Payload models.Redirect
	}{
		Ctx:     ctx,
		Options: options,
		ID:      id,
		Payload: payload,
	}
	mock.lockPutRedirect.Lock()
	mock.calls.PutRedirect = append(mock.calls.PutRedirect, callInfo)
	mock.lockPutRedirect.Unlock()
	return mock.PutRedirectFunc(ctx, options, id, payload)
}

// PutRedirectCalls gets all the calls that were made to PutRedirect.
// Check the length with:
//
//	len(mockedClienter.PutRedirectCalls())
func (mock *ClienterMock) PutRedirectCalls() []struct {
	Ctx     context.Context
	Options sdk.Options
	ID      string
	Payload models.Redirect
} {
	var calls []struct {
		Ctx     context.Context
		Options sdk.Options
		ID      string
		Payload models.Redirect
	}
	mock.lockPutRedirect.RLock()
	calls = mock.calls.PutRedirect
	mock.lockPutRedirect.RUnlock()
	return calls
}

// URL calls URLFunc.
func (mock *ClienterMock) URL() string {
	if mock.URLFunc == nil {
		panic("ClienterMock.URLFunc: method is nil but Clienter.URL was just called")
	}
	callInfo := struct {
	}{}
	mock.lockURL.Lock()
	mock.calls.URL = append(mock.calls.URL, callInfo)
	mock.lockURL.Unlock()
	return mock.URLFunc()
}

// URLCalls gets all the calls that were made to URL.
// Check the length with:
//
//	len(mockedClienter.URLCalls())
func (mock *ClienterMock) URLCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockURL.RLock()
	calls = mock.calls.URL
	mock.lockURL.RUnlock()
	return calls
}
