// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storetest

import (
	"context"
	"github.com/ONSdigital/dis-redirect-api/store"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/redis/go-redis/v9"
	"sync"
	"time"
)

// Ensure, that StorerMock does implement store.Storer.
// If this is not the case, regenerate this file with moq.
var _ store.Storer = &StorerMock{}

// StorerMock is a mock implementation of store.Storer.
//
//	func TestSomethingThatUsesStorer(t *testing.T) {
//
//		// make and configure a mocked store.Storer
//		mockedStorer := &StorerMock{
//			CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			DeleteValueFunc: func(ctx context.Context, key string) error {
//				panic("mock out the DeleteValue method")
//			},
//			GetKeyValuePairsFunc: func(ctx context.Context, matchPattern string, count int64, cursor uint64) (map[string]string, uint64, error) {
//				panic("mock out the GetKeyValuePairs method")
//			},
//			GetKeysFunc: func(ctx context.Context, matchPattern string, count int64, cursor uint64) ([]string, uint64, error) {
//				panic("mock out the GetKeys method")
//			},
//			GetSetMemberCountFunc: func(ctx context.Context, setKey string) (int64, error) {
//				panic("mock out the GetSetMemberCount method")
//			},
//			GetSetMemberValuesFunc: func(ctx context.Context, setKey string, matchPattern string, valuePrefix string, count int64, cursor uint64) (map[string]string, uint64, error) {
//				panic("mock out the GetSetMemberValues method")
//			},
//			GetTotalKeysFunc: func(ctx context.Context) (int64, error) {
//				panic("mock out the GetTotalKeys method")
//			},
//			GetValueFunc: func(ctx context.Context, key string) (string, error) {
//				panic("mock out the GetValue method")
//			},
//			SetValueFunc: func(ctx context.Context, key string, value interface{}, expiration time.Duration) error {
//				panic("mock out the SetValue method")
//			},
//			TransactionFunc: func(ctx context.Context, queue func(redis.Pipeliner)) ([]redis.Cmder, error) {
//				panic("mock out the Transaction method")
//			},
//		}
//
//		// use mockedStorer in code that requires store.Storer
//		// and then make assertions.
//
//	}
type StorerMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// DeleteValueFunc mocks the DeleteValue method.
	DeleteValueFunc func(ctx context.Context, key string) error

	// GetKeyValuePairsFunc mocks the GetKeyValuePairs method.
	GetKeyValuePairsFunc func(ctx context.Context, matchPattern string, count int64, cursor uint64) (map[string]string, uint64, error)

	// GetKeysFunc mocks the GetKeys method.
	GetKeysFunc func(ctx context.Context, matchPattern string, count int64, cursor uint64) ([]string, uint64, error)

	// GetSetMemberCountFunc mocks the GetSetMemberCount method.
	GetSetMemberCountFunc func(ctx context.Context, setKey string) (int64, error)

	// GetSetMemberValuesFunc mocks the GetSetMemberValues method.
	GetSetMemberValuesFunc func(ctx context.Context, setKey string, matchPattern string, valuePrefix string, count int64, cursor uint64) (map[string]string, uint64, error)

	// GetTotalKeysFunc mocks the GetTotalKeys method.
	GetTotalKeysFunc func(ctx context.Context) (int64, error)

	// GetValueFunc mocks the GetValue method.
	GetValueFunc func(ctx context.Context, key string) (string, error)

	// SetValueFunc mocks the SetValue method.
	SetValueFunc func(ctx context.Context, key string, value interface{}, expiration time.Duration) error

	// TransactionFunc mocks the Transaction method.
	TransactionFunc func(ctx context.Context, queue func(redis.Pipeliner)) ([]redis.Cmder, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// DeleteValue holds details about calls to the DeleteValue method.
		DeleteValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetKeyValuePairs holds details about calls to the GetKeyValuePairs method.
		GetKeyValuePairs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MatchPattern is the matchPattern argument value.
			MatchPattern string
			// Count is the count argument value.
			Count int64
			// Cursor is the cursor argument value.
			Cursor uint64
		}
		// GetKeys holds details about calls to the GetKeys method.
		GetKeys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MatchPattern is the matchPattern argument value.
			MatchPattern string
			// Count is the count argument value.
			Count int64
			// Cursor is the cursor argument value.
			Cursor uint64
		}
		// GetSetMemberCount holds details about calls to the GetSetMemberCount method.
		GetSetMemberCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SetKey is the setKey argument value.
			SetKey string
		}
		// GetSetMemberValues holds details about calls to the GetSetMemberValues method.
		GetSetMemberValues []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SetKey is the setKey argument value.
			SetKey string
			// MatchPattern is the matchPattern argument value.
			MatchPattern string
			// ValuePrefix is the valuePrefix argument value.
			ValuePrefix string
			// Count is the count argument value.
			Count int64
			// Cursor is the cursor argument value.
			Cursor uint64
		}
		// GetTotalKeys holds details about calls to the GetTotalKeys method.
		GetTotalKeys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetValue holds details about calls to the GetValue method.
		GetValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// SetValue holds details about calls to the SetValue method.
		SetValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value interface{}
			// Expiration is the expiration argument value.
			Expiration time.Duration
		}
		// Transaction holds details about calls to the Transaction method.
		Transaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Queue is the queue argument value.
			Queue func(redis.Pipeliner)
		}
	}
	lockChecker            sync.RWMutex
	lockDeleteValue        sync.RWMutex
	lockGetKeyValuePairs   sync.RWMutex
	lockGetKeys            sync.RWMutex
	lockGetSetMemberCount  sync.RWMutex
	lockGetSetMemberValues sync.RWMutex
	lockGetTotalKeys       sync.RWMutex
	lockGetValue           sync.RWMutex
	lockSetValue           sync.RWMutex
	lockTransaction        sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *StorerMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("StorerMock.CheckerFunc: method is nil but Storer.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedStorer.CheckerCalls())
func (mock *StorerMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// DeleteValue calls DeleteValueFunc.
func (mock *StorerMock) DeleteValue(ctx context.Context, key string) error {
	if mock.DeleteValueFunc == nil {
		panic("StorerMock.DeleteValueFunc: method is nil but Storer.DeleteValue was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDeleteValue.Lock()
	mock.calls.DeleteValue = append(mock.calls.DeleteValue, callInfo)
	mock.lockDeleteValue.Unlock()
	return mock.DeleteValueFunc(ctx, key)
}

// DeleteValueCalls gets all the calls that were made to DeleteValue.
// Check the length with:
//
//	len(mockedStorer.DeleteValueCalls())
func (mock *StorerMock) DeleteValueCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDeleteValue.RLock()
	calls = mock.calls.DeleteValue
	mock.lockDeleteValue.RUnlock()
	return calls
}

// GetKeyValuePairs calls GetKeyValuePairsFunc.
func (mock *StorerMock) GetKeyValuePairs(ctx context.Context, matchPattern string, count int64, cursor uint64) (map[string]string, uint64, error) {
	if mock.GetKeyValuePairsFunc == nil {
		panic("StorerMock.GetKeyValuePairsFunc: method is nil but Storer.GetKeyValuePairs was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		MatchPattern string
		Count        int64
		Cursor       uint64
	}{
		Ctx:          ctx,
		MatchPattern: matchPattern,
		Count:        count,
		Cursor:       cursor,
	}
	mock.lockGetKeyValuePairs.Lock()
	mock.calls.GetKeyValuePairs = append(mock.calls.GetKeyValuePairs, callInfo)
	mock.lockGetKeyValuePairs.Unlock()
	return mock.GetKeyValuePairsFunc(ctx, matchPattern, count, cursor)
}

// GetKeyValuePairsCalls gets all the calls that were made to GetKeyValuePairs.
// Check the length with:
//
//	len(mockedStorer.GetKeyValuePairsCalls())
func (mock *StorerMock) GetKeyValuePairsCalls() []struct {
	Ctx          context.Context
	MatchPattern string
	Count        int64
	Cursor       uint64
} {
	var calls []struct {
		Ctx          context.Context
		MatchPattern string
		Count        int64
		Cursor       uint64
	}
	mock.lockGetKeyValuePairs.RLock()
	calls = mock.calls.GetKeyValuePairs
	mock.lockGetKeyValuePairs.RUnlock()
	return calls
}

// GetKeys calls GetKeysFunc.
func (mock *StorerMock) GetKeys(ctx context.Context, matchPattern string, count int64, cursor uint64) ([]string, uint64, error) {
	if mock.GetKeysFunc == nil {
		panic("StorerMock.GetKeysFunc: method is nil but Storer.GetKeys was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		MatchPattern string
		Count        int64
		Cursor       uint64
	}{
		Ctx:          ctx,
		MatchPattern: matchPattern,
		Count:        count,
		Cursor:       cursor,
	}
	mock.lockGetKeys.Lock()
	mock.calls.GetKeys = append(mock.calls.GetKeys, callInfo)
	mock.lockGetKeys.Unlock()
	return mock.GetKeysFunc(ctx, matchPattern, count, cursor)
}

// GetKeysCalls gets all the calls that were made to GetKeys.
// Check the length with:
//
//	len(mockedStorer.GetKeysCalls())
func (mock *StorerMock) GetKeysCalls() []struct {
	Ctx          context.Context
	MatchPattern string
	Count        int64
	Cursor       uint64
} {
	var calls []struct {
		Ctx          context.Context
		MatchPattern string
		Count        int64
		Cursor       uint64
	}
	mock.lockGetKeys.RLock()
	calls = mock.calls.GetKeys
	mock.lockGetKeys.RUnlock()
	return calls
}

// GetSetMemberCount calls GetSetMemberCountFunc.
func (mock *StorerMock) GetSetMemberCount(ctx context.Context, setKey string) (int64, error) {
	if mock.GetSetMemberCountFunc == nil {
		panic("StorerMock.GetSetMemberCountFunc: method is nil but Storer.GetSetMemberCount was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		SetKey string
	}{
		Ctx:    ctx,
		SetKey: setKey,
	}
	mock.lockGetSetMemberCount.Lock()
	mock.calls.GetSetMemberCount = append(mock.calls.GetSetMemberCount, callInfo)
	mock.lockGetSetMemberCount.Unlock()
	return mock.GetSetMemberCountFunc(ctx, setKey)
}

// GetSetMemberCountCalls gets all the calls that were made to GetSetMemberCount.
// Check the length with:
//
//	len(mockedStorer.GetSetMemberCountCalls())
func (mock *StorerMock) GetSetMemberCountCalls() []struct {
	Ctx    context.Context
	SetKey string
} {
	var calls []struct {
		Ctx    context.Context
		SetKey string
	}
	mock.lockGetSetMemberCount.RLock()
	calls = mock.calls.GetSetMemberCount
	mock.lockGetSetMemberCount.RUnlock()
	return calls
}

// GetSetMemberValues calls GetSetMemberValuesFunc.
func (mock *StorerMock) GetSetMemberValues(ctx context.Context, setKey string, matchPattern string, valuePrefix string, count int64, cursor uint64) (map[string]string, uint64, error) {
	if mock.GetSetMemberValuesFunc == nil {
		panic("StorerMock.GetSetMemberValuesFunc: method is nil but Storer.GetSetMemberValues was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		SetKey       string
		MatchPattern string
		ValuePrefix  string
		Count        int64
		Cursor       uint64
	}{
		Ctx:          ctx,
		SetKey:       setKey,
		MatchPattern: matchPattern,
		ValuePrefix:  valuePrefix,
		Count:        count,
		Cursor:       cursor,
	}
	mock.lockGetSetMemberValues.Lock()
	mock.calls.GetSetMemberValues = append(mock.calls.GetSetMemberValues, callInfo)
	mock.lockGetSetMemberValues.Unlock()
	return mock.GetSetMemberValuesFunc(ctx, setKey, matchPattern, valuePrefix, count, cursor)
}

// GetSetMemberValuesCalls gets all the calls that were made to GetSetMemberValues.
// Check the length with:
//
//	len(mockedStorer.GetSetMemberValuesCalls())
func (mock *StorerMock) GetSetMemberValuesCalls() []struct {
	Ctx          context.Context
	SetKey       string
	MatchPattern string
	ValuePrefix  string
	Count        int64
	Cursor       uint64
} {
	var calls []struct {
		Ctx          context.Context
		SetKey       string
		MatchPattern string
		ValuePrefix  string
		Count        int64
		Cursor       uint64
	}
	mock.lockGetSetMemberValues.RLock()
	calls = mock.calls.GetSetMemberValues
	mock.lockGetSetMemberValues.RUnlock()
	return calls
}

// GetTotalKeys calls GetTotalKeysFunc.
func (mock *StorerMock) GetTotalKeys(ctx context.Context) (int64, error) {
	if mock.GetTotalKeysFunc == nil {
		panic("StorerMock.GetTotalKeysFunc: method is nil but Storer.GetTotalKeys was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetTotalKeys.Lock()
	mock.calls.GetTotalKeys = append(mock.calls.GetTotalKeys, callInfo)
	mock.lockGetTotalKeys.Unlock()
	return mock.GetTotalKeysFunc(ctx)
}

// GetTotalKeysCalls gets all the calls that were made to GetTotalKeys.
// Check the length with:
//
//	len(mockedStorer.GetTotalKeysCalls())
func (mock *StorerMock) GetTotalKeysCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetTotalKeys.RLock()
	calls = mock.calls.GetTotalKeys
	mock.lockGetTotalKeys.RUnlock()
	return calls
}

// GetValue calls GetValueFunc.
func (mock *StorerMock) GetValue(ctx context.Context, key string) (string, error) {
	if mock.GetValueFunc == nil {
		panic("StorerMock.GetValueFunc: method is nil but Storer.GetValue was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGetValue.Lock()
	mock.calls.GetValue = append(mock.calls.GetValue, callInfo)
	mock.lockGetValue.Unlock()
	return mock.GetValueFunc(ctx, key)
}

// GetValueCalls gets all the calls that were made to GetValue.
// Check the length with:
//
//	len(mockedStorer.GetValueCalls())
func (mock *StorerMock) GetValueCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGetValue.RLock()
	calls = mock.calls.GetValue
	mock.lockGetValue.RUnlock()
	return calls
}

// SetValue calls SetValueFunc.
func (mock *StorerMock) SetValue(ctx context.Context, key string, value interface{}, expiration time.Duration) error {
	if mock.SetValueFunc == nil {
		panic("StorerMock.SetValueFunc: method is nil but Storer.SetValue was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Key        string
		Value      interface{}
		Expiration time.Duration
	}{
		Ctx:        ctx,
		Key:        key,
		Value:      value,
		Expiration: expiration,
	}
	mock.lockSetValue.Lock()
	mock.calls.SetValue = append(mock.calls.SetValue, callInfo)
	mock.lockSetValue.Unlock()
	return mock.SetValueFunc(ctx, key, value, expiration)
}

// SetValueCalls gets all the calls that were made to SetValue.
// Check the length with:
//
//	len(mockedStorer.SetValueCalls())
func (mock *StorerMock) SetValueCalls() []struct {
	Ctx        context.Context
	Key        string
	Value      interface{}
	Expiration time.Duration
} {
	var calls []struct {
		Ctx        context.Context
		Key        string
		Value      interface{}
		Expiration time.Duration
	}
	mock.lockSetValue.RLock()
	calls = mock.calls.SetValue
	mock.lockSetValue.RUnlock()
	return calls
}

// Transaction calls TransactionFunc.
func (mock *StorerMock) Transaction(ctx context.Context, queue func(redis.Pipeliner)) ([]redis.Cmder, error) {
	if mock.TransactionFunc == nil {
		panic("StorerMock.TransactionFunc: method is nil but Storer.Transaction was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Queue func(redis.Pipeliner)
	}{
		Ctx:   ctx,
		Queue: queue,
	}
	mock.lockTransaction.Lock()
	mock.calls.Transaction = append(mock.calls.Transaction, callInfo)
	mock.lockTransaction.Unlock()
	return mock.TransactionFunc(ctx, queue)
}

// TransactionCalls gets all the calls that were made to Transaction.
// Check the length with:
//
//	len(mockedStorer.TransactionCalls())
func (mock *StorerMock) TransactionCalls() []struct {
	Ctx   context.Context
	Queue func(redis.Pipeliner)
} {
	var calls []struct {
		Ctx   context.Context
		Queue func(redis.Pipeliner)
	}
	mock.lockTransaction.RLock()
	calls = mock.calls.Transaction
	mock.lockTransaction.RUnlock()
	return calls
}
